---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/pancakestore.site
    - /bin/cp -f index.html $DEPLOYPATH/
    - /bin/cp -Rf css $DEPLOYPATH/
    - /bin/cp -Rf js $DEPLOYPATH/
    - /bin/cp -Rf assets $DEPLOYPATH/
    - /bin/cp -f PancakeStore.zip $DEPLOYPATH/
